### ISSUE TITLE
Формат отображения времени

### ISSUE THREAD

**Issue by WhyWeLive** [CollegeSchedule/cs-schedule#3]
Сейчас на главном экране время отображается в минутах, но без часов. А именно "67 минут до начала пары", что не особо выглядит хорошо. Нужно отображать используясь следующий формат HH:mm.

**Comment by ChAyLom** [comment]
Теперь время отображается в формате "До начала пары _hh_ ч _mm_ мин" если больше часа, и "До начала пары _mm_ мин" если меньше часа, например "До начала пары 1 ч 7 мин" и "До начала пары 44 мин".
